name: first workflow
on:  workflow_dispatch
jobs:
  first-job:
    runs-on:  ubuntu-latest
    steps:
    - name:  print greeting
      run:  echo "hello world"
    - name:  print echo good bye
      run:  echo "done - bye"
